# Generated by Django 2.2.28 on 2026-03-22 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-posted'], 'verbose_name': 'Статья блога', 'verbose_name_plural': 'Статьи блога'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 3, 22, 23, 35, 12, 521030), verbose_name='Опубликована'),
        ),
        migrations.AlterModelTable(
            name='blog',
            table='Posts',
        ),
    ]
