# Generated by Django 2.2.28 on 2026-04-28 18:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20260417_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории каталога')),
                ('description', models.TextField(verbose_name='Описание категории каталога')),
            ],
            options={
                'verbose_name': 'Категории каталога',
                'verbose_name_plural': 'Категории каталога',
                'db_table': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 28, 21, 17, 44, 220330), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 28, 21, 17, 44, 220330), verbose_name='Опубликовано'),
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название элемента каталога')),
                ('description', models.TextField(verbose_name='Краткое описание элемента каталога')),
                ('content', models.TextField(verbose_name='Полное описание элемента каталога')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена элемента каталога')),
                ('image', models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к картинке элемента каталога')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='Категория каталога')),
            ],
            options={
                'verbose_name': 'Элемент каталога',
                'verbose_name_plural': 'Элемент каталога',
                'db_table': 'Elements',
                'ordering': ['title'],
            },
        ),
    ]
